### ISSUE TITLE
userInfo is not defined

### ISSUE THREAD

**Issue by Joan1590** [AxelConceicao/bustabit-script-simulator-2020#5]
Hi !!

The documentation allow the UserInfo information: https://github.com/bustabit/autobet 

But if you run a script here, doesnt work, i get the error message: 

ReferenceError: userInfo is not defined

**Comment by AxelConceicao** [comment]
Hey @Joan1590 I didn't include the UserInfo store because I've never seen any scripts who needs these properties to work:
- userInfo.balance: User balance in satoshis
- userInfo.bets: Total amount of user's bets
- userInfo.wagered: Total amount of satoshis user has wagered
- userInfo.invested: Total amount user has invested in the bankroll
- userInfo.profit
- userInfo.unpaidDeposits

Maybe I'm wrong tbh

**Comment by Joan1590** [comment]
Hi !! I make a fork, see this: https://github.com/Joan1590/bustabit-script-simulator 

Now is not longer required the file with the games preloaders, only with the hash, the engine file going to create the games, with the same struct like the txt files index:hash:bust

And i have two scripts extras, that i used on bustabit site
